name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        uses: ./.github/actions/setup
      - name: rye lint
        run: rye lint

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        uses: ./.github/actions/setup
      - name: rye fmt
        run: rye fmt --check
